### ISSUE TITLE
Provide a owncloud-docker/server variant with PHP 7.1.0

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud-ci/server#1]
Binding the contents of the [daily-master tarball](http://download.owncloud.org/community/owncloud-daily-master.tar.bz2) on `owncloud/server:latest`'s `/var/www/owncloud` dir. results on:

```
This version of ownCloud requires at least PHP 7.1.0
You are currently running PHP 7.0.22-0ubuntu0.16.04.1. Please update your PHP version.
```

Would be convenient to have a image for such purpose. Since `master` is unstable I think this fits better in here - feel free to move it to `owncloud-docker` orga. in case you think otherwise. 

cc/ @tboerger @patrickjahns

**Comment by patrickjahns** [comment]
The idea was to use` owncloudci/php` as base for the `owncloud/base` image - and then mount the core inside.

That would allow for testing with php5.6 - php7.2 

As `owncloud/server` and `owncloud/base` right now is production images - I don't see if fit there - right idea to accomplish this in the owncloudci images

**Comment by patrickjahns** [comment]
closing here - will be addressed with: https://github.com/owncloud-ci/base/pull/1 

please note - the difference between `server` and `base` - `server` is `base` + owncloud tarball on top.
